import { initAccordion } from '@/scripts/accordion';
import { initArticleToc } from '@/scripts/article-toc';
import { initArchiveFilter } from '@/scripts/archive-filter';
import '@/scripts/archive-facets';
import '@/scripts/collection-filter';
import { initFooterReveal } from '@/scripts/footer-reveal';
import { initHeader } from '@/scripts/header';
import { initImageGalleries } from '@/scripts/image-gallery';
import { initLoadingScreen } from '@/scripts/loading-screen';
import { initReveal } from '@/scripts/reveal';
import { initScrollProgress } from '@/scripts/scroll-progress';
import { initSelectedWorkTabs } from '@/scripts/selected-work-tabs';
import { initSelect } from '@/scripts/select';
import { initSliders } from '@/scripts/slider';
import '@/scripts/entry-index';
import '@/scripts/products';
import '@/scripts/reader';

initLoadingScreen();
initHeader();
initImageGalleries();
initScrollProgress();
initAccordion();
initArticleToc();
initArchiveFilter();
initSelect();
initFooterReveal();
initSliders();
initReveal();
initSelectedWorkTabs();
