import { twJoin } from "@/utils/cn";
export const skipLinkClasses = twJoin(
	"sr-only",
	"focus:not-sr-only",
	"focus:fixed",
	"focus:left-4",
	"focus:top-4",
	"focus:z-50",
	"focus:rounded-md",
	"focus:bg-blue-600",
	"focus:px-4",
	"focus:py-3",
	"focus:text-sm",
	"focus:font-semibold",
	"focus:text-black",
	"focus:outline-none",
	"focus:ring-2",
	"focus:ring-blue-600",
	"focus:ring-offset-2",
	"focus:transition-all",
	"focus:duration-200",
);
