export const articleRichTextClasses = [
	"text-neutral-700",
	"[&_p]:mt-6 [&_p]:leading-8",
	"[&_h2]:mt-12 [&_h2]:scroll-mt-28 [&_h2]:text-3xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-neutral-950",
	"[&_h3]:mt-9 [&_h3]:scroll-mt-28 [&_h3]:text-2xl [&_h3]:font-semibold [&_h3]:tracking-tight [&_h3]:text-neutral-950",
	"[&_ul]:mt-6 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6",
	"[&_ol]:mt-6 [&_ol]:list-decimal [&_ol]:space-y-2 [&_ol]:pl-6",
	"[&_li]:leading-7",
	"[&_strong]:font-semibold [&_strong]:text-neutral-950",
	"[&_a]:font-medium [&_a]:text-blue-700 [&_a]:underline [&_a]:underline-offset-4",
	"[&_blockquote]:mt-8 [&_blockquote]:border-l-2 [&_blockquote]:border-neutral-300 [&_blockquote]:pl-5 [&_blockquote]:italic",
	"[&_hr]:my-10 [&_hr]:border-neutral-200",
	"[&_img]:my-8 [&_img]:h-auto [&_img]:w-full [&_img]:rounded-lg",
	"[&_pre]:mt-8 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:bg-neutral-950 [&_pre]:p-5 [&_pre]:text-sm [&_pre]:text-neutral-100",
	"[&_code]:text-sm",
	"[&_p_code]:rounded [&_p_code]:bg-neutral-100 [&_p_code]:px-1.5 [&_p_code]:py-0.5 [&_p_code]:text-neutral-900",
	"[&_table]:mt-8 [&_table]:w-full [&_table]:border-collapse [&_table]:text-left [&_table]:text-sm",
	"[&_th]:border-b [&_th]:border-neutral-300 [&_th]:px-3 [&_th]:py-3 [&_th]:font-semibold [&_th]:text-neutral-950",
	"[&_td]:border-b [&_td]:border-neutral-200 [&_td]:px-3 [&_td]:py-3",
].join(" ");
