import { z } from "astro/zod";
import {
	cardColumnsSchema,
	cardConfigSchema,
	cardGapSchema,
	cardLayoutSchema,
	cardTemplateSchema,
} from "@/content/card-config-schema";

const optionSchema = z.object({
	label: z.string().min(1),
	value: z.string().min(1),
});

const catalogCardConfigSchema = cardConfigSchema.extend({
	template: cardTemplateSchema,
	layout: cardLayoutSchema,
	columns: cardColumnsSchema,
	gap: cardGapSchema,
});

const panelSchema = z.object({
	surface: z.enum([
		"plain",
		"accent",
		"bordered",
		"canvas",
		"dark",
		"glass",
		"glass-dark",
		"soft",
	]),
	radius: z.enum(["none", "md", "lg"]),
	spacing: z.enum(["none", "xs", "sm", "md", "lg", "xl"]),
});

const genreIconSchema = z.enum([
	"arrowLeft",
	"arrowRight",
	"arrowUp",
	"arrowUpRight",
	"arrowPath",
	"archiveBox",
	"bars3",
	"bolt",
	"chevronLeft",
	"chevronDown",
	"chevronRight",
	"github",
	"globeAlt",
	"lightBulb",
	"linkedin",
	"xMark",
	"folder01",
	"facebook",
	"link",
	"twitter",
	"userCircle",
	"calendar03",
	"check",
	"clock01",
	"gridView",
	"listView",
	"play",
	"search",
	"shoppingBag",
	"star",
	"questionMarkCircle",
	"bookOpen",
	"bookmark",
	"eye",
	"lockClosed",
	"adjustmentsHorizontal",
	"moon",
	"handThumbUp",
	"heart",
	"faceSmile",
	"faceFrown",
]);

export const publicationCatalogSettingsSchema = z.object({
	toolbar: z.object({
		searchLabel: z.string().min(1),
		searchPlaceholder: z.string().min(1),
		genreLabel: z.string().min(1),
		allGenresLabel: z.string().min(1),
		statusLabel: z.string().min(1),
		allStatusesLabel: z.string().min(1),
		ongoingLabel: z.string().min(1),
		completeLabel: z.string().min(1),
		sortLabel: z.string().min(1),
		sortValue: z.string().min(1),
		sortOptions: z.array(optionSchema).min(1),
		viewLabel: z.string().min(1),
		gridViewLabel: z.string().min(1),
		listViewLabel: z.string().min(1),
	}),
	sidebar: z.object({
		labelTemplate: z.string().min(1),
		position: z.enum(["start", "end"]),
		sticky: z.boolean(),
		genresLegend: z.string().min(1),
		allGenresShortLabel: z.string().min(1),
		panel: panelSchema,
		trendingTitle: z.string().min(1),
		popularAuthorsTitle: z.string().min(1),
		listCards: catalogCardConfigSchema,
		authorPlaceholder: z.object({
			src: z.string().min(1),
			width: z.number().int().positive(),
			height: z.number().int().positive(),
		}),
		trendingLimit: z.number().int().positive(),
		authorLimit: z.number().int().positive(),
	}),
	main: z.object({
		featuredTitle: z.string().min(1),
		latestTitle: z.string().min(1),
		popularGenresTitle: z.string().min(1),
		topRatedTitle: z.string().min(1),
		completedTitle: z.string().min(1),
		allStoriesTitle: z.string().min(1),
		featuredLimit: z.number().int().positive(),
		latestLimit: z.number().int().positive(),
		popularGenresLimit: z.number().int().positive(),
		topRatedLimit: z.number().int().positive(),
		completedLimit: z.number().int().positive(),
		allStoriesPageSize: z.number().int().positive(),
		allStoriesPagination: z.object({
			label: z.string().min(1),
			previousLabel: z.string().min(1),
			nextLabel: z.string().min(1),
		}),
		featuredCards: catalogCardConfigSchema,
		latestCards: catalogCardConfigSchema,
		genreCards: catalogCardConfigSchema,
		topRatedCards: catalogCardConfigSchema,
		completedCards: catalogCardConfigSchema,
		allStoriesCards: catalogCardConfigSchema,
		genreIcons: z.array(genreIconSchema).min(1),
		genreWorksTemplate: z.string().min(1),
		authorWorksTemplate: z.string().min(1),
	}),
});
