import { z } from "astro/zod";

const navigationItemSchema = z.object({ href: z.string().min(1), label: z.string().min(1) });
const socialLinkSchema = navigationItemSchema.extend({ shortLabel: z.string().min(1), icon: z.enum(["github", "linkedin"]).optional() });
const systemStateActionSchema = z.object({ href: z.string().min(1), label: z.string().min(1), icon: z.enum(["arrowLeft", "arrowRight", "arrowUp", "arrowUpRight", "chevronLeft", "chevronRight"]).optional() });
const imageSchema = z.object({ src: z.string().min(1), alt: z.string(), width: z.number().int().positive(), height: z.number().int().positive() });
const systemStateSchema = z.object({ id: z.string().min(1), displayCode: z.string().min(1).optional(), eyebrow: z.string().min(1), title: z.string().min(1), description: z.string().min(1), primaryAction: systemStateActionSchema, secondaryAction: systemStateActionSchema.optional(), image: imageSchema, metadataTitle: z.string().min(1), metadataDescription: z.string().min(1) });
export const siteSettingsSchema = z.object({ site: z.object({ name: z.string().min(1), shortName: z.string().min(1), role: z.string().min(1), location: z.string().min(1), email: z.email(), logo: z.string().optional(), logoLight: z.string().optional(), logoDark: z.string().optional(), favicon: z.string().optional(), contactLabel: z.string().min(1) }), metadata: z.object({ language: z.string().min(2), title: z.string().min(1), description: z.string().min(1) }) });
export const navigationSettingsSchema = z.object({ navItems: z.array(navigationItemSchema), footerNavItems: z.array(navigationItemSchema), resourceLinks: z.array(navigationItemSchema), legalLinks: z.array(navigationItemSchema), socialLinks: z.array(socialLinkSchema) });

const pageSectionSettingsSchema = z.object({ theme: z.enum(["dark", "light", "canvas", "accent", "none"]), spacing: z.enum(["compact", "default", "none", "lead", "body", "closing"]), container: z.enum(["site", "content", "none"]), layout: z.string().optional(), columns: z.number().int().positive().optional(), gap: z.string().optional(), mediaRatio: z.string().optional(), separator: z.string().optional() });
const pageActionSchema = z.object({ href: z.string().min(1), label: z.string().min(1), icon: z.string().optional(), iconPosition: z.enum(["start", "end"]).optional(), variant: z.string().optional(), tone: z.string().optional(), size: z.string().optional() });
const pageHeadingSchema = z.object({ number: z.string().optional(), label: z.string().optional(), title: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]), description: z.string().optional(), action: pageActionSchema.optional() });
const pageCardConfigSchema = z.object({ template: z.string().optional(), layout: z.string().optional(), columns: z.number().int().positive().optional(), gap: z.string().optional(), mediaRatio: z.string().optional(), separator: z.string().optional(), headingLevel: z.number().int().min(1).max(6).optional(), slots: z.record(z.string(), z.boolean()).optional() });
const optionSchema = z.object({ label: z.string().min(1), value: z.string().min(1) });
const searchControlSchema = z.object({ id: z.string().min(1), label: z.string().min(1), name: z.string().min(1), placeholder: z.string().min(1) });
const viewControlSchema = z.object({ label: z.string().min(1), gridLabel: z.string().min(1), listLabel: z.string().min(1) });
const paginationSchema = z.object({ label: z.string().min(1), previousLabel: z.string().min(1), nextLabel: z.string().min(1), pageSize: z.number().int().positive() });
const filterGroupSchema = z.object({ appearance: z.string().min(1), control: z.string().min(1), legend: z.string().min(1), name: z.string().min(1), type: z.enum(["radio", "checkbox"]) });

const projectCardPresentationSchema = z.object({ routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1), tagBase: z.string().min(1) }), actionLabel: z.string().optional(), actionIcon: z.string().optional(), separator: z.string(), size: z.string().optional(), tagsLabel: z.string().optional(), lightAppearance: z.string().min(1), darkAppearance: z.string().min(1), metadataDisplay: z.string().min(1), imageWidth: z.number().int().positive(), imageHeight: z.number().int().positive() });
const labCardPresentationSchema = z.object({ routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1), technologyBase: z.string().min(1) }), ariaLabelPrefix: z.string(), categoryDisplay: z.string().min(1), completeBadgeTone: z.string().min(1), activeBadgeTone: z.string().min(1), tagsLabelSuffix: z.string(), metricIcons: z.tuple([z.string().min(1), z.string().min(1), z.string().min(1)]) });
const productCardPresentationSchema = z.object({ routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1) }), ariaLabelPrefix: z.string(), imageAltSuffix: z.string(), imageWidth: z.number().int().positive(), imageHeight: z.number().int().positive(), categoryDisplay: z.string().min(1), actionHref: z.string().min(1), actionLabelPrefix: z.string(), actionIcon: z.string().min(1), license: z.string().min(1) });
const insightCardPresentationSchema = z.object({ routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1), tagBase: z.string().min(1) }), separator: z.string(), metadataDisplay: z.string().min(1), tagsLabelSuffix: z.string(), imageWidth: z.number().int().positive(), imageHeight: z.number().int().positive() });
const publicationCardPresentationSchema = z.object({ routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1) }), ariaLabelPrefix: z.string(), categoryDisplay: z.string().min(1), tagsLabelSuffix: z.string(), viewsIcon: z.string().min(1) });
const staticCardItemSchema = z.record(z.string(), z.unknown());
const collectionSectionBase = { id: z.string().min(1), type: z.literal("collection"), template: z.string().optional(), settings: pageSectionSettingsSchema };
const collectionContentBase = { heading: pageHeadingSchema.optional(), cards: pageCardConfigSchema.optional() };
const staticCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, items: z.array(staticCardItemSchema).min(1) }) });
const productsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("products"), limit: z.number().int().positive().optional() }), itemPresentation: productCardPresentationSchema }) });
const projectsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("projects"), limit: z.number().int().positive().optional() }), itemPresentation: projectCardPresentationSchema }) });
const labsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("labs"), limit: z.number().int().positive().optional() }), itemPresentation: labCardPresentationSchema }) });
const blogCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("blog"), limit: z.number().int().positive().optional() }), itemPresentation: insightCardPresentationSchema }) });
const comicsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("comics"), limit: z.number().int().positive().optional() }), itemPresentation: publicationCardPresentationSchema }) });
const novelsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("novels"), limit: z.number().int().positive().optional() }), itemPresentation: publicationCardPresentationSchema }) });
const publicationsCollectionSectionSchema = z.object({ ...collectionSectionBase, content: z.object({ ...collectionContentBase, source: z.object({ collection: z.literal("publications"), limit: z.number().int().positive().optional() }), itemPresentation: z.object({ comics: publicationCardPresentationSchema, novels: publicationCardPresentationSchema }) }) });

const projectsArchiveSectionSchema = z.object({ id: z.string().min(1), type: z.literal("archive"), template: z.literal("taxonomy"), settings: pageSectionSettingsSchema, content: z.object({ source: z.object({ collection: z.literal("projects") }), routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1), tagBase: z.string().min(1) }), taxonomy: z.object({ categoryPrefix: z.string().min(1), tagPrefix: z.string().min(1) }), toolbar: z.object({ filterLabel: z.string().min(1), allLabel: z.string().min(1), allValue: z.string().min(1), sortLabel: z.string().min(1), sortValue: z.string().min(1), sortOptions: z.array(optionSchema).min(1), viewLabel: z.string().min(1), gridViewLabel: z.string().min(1), listViewLabel: z.string().min(1) }), itemPresentation: projectCardPresentationSchema, cards: pageCardConfigSchema, emptyLabel: z.string().min(1), pagination: paginationSchema }) });
const labsArchiveSectionSchema = z.object({ id: z.string().min(1), type: z.literal("archive"), template: z.literal("faceted"), settings: pageSectionSettingsSchema, content: z.object({ source: z.object({ collection: z.literal("labs") }), toolbar: z.object({ search: searchControlSchema, selects: z.array(z.object({ control: z.string().min(1), id: z.string().min(1), label: z.string().min(1), value: z.string().min(1), options: z.array(optionSchema).min(1) })), sort: z.object({ label: z.string().min(1), value: z.string().min(1), options: z.array(optionSchema).min(1) }), view: viewControlSchema }), sidebar: z.object({ label: z.string().min(1), filterLabel: z.string().min(1), category: filterGroupSchema.extend({ allLabel: z.string().min(1), allValue: z.string().min(1), allHref: z.string().min(1) }), technology: filterGroupSchema }), routes: z.object({ categoryBase: z.string().min(1), technologyBase: z.string().min(1) }), itemPresentation: labCardPresentationSchema, resultLabel: z.string().min(1), cards: pageCardConfigSchema, emptyLabel: z.string().min(1), pagination: paginationSchema }) });
const productsArchiveSectionSchema = z.object({ id: z.string().min(1), type: z.literal("archive"), template: z.literal("faceted"), settings: pageSectionSettingsSchema, content: z.object({ source: z.object({ collection: z.literal("products") }), routes: z.object({ base: z.string().min(1), categoryBase: z.string().min(1) }), toolbar: z.object({ search: searchControlSchema, category: z.object({ control: z.string().min(1), id: z.string().min(1), label: z.string().min(1), value: z.string().min(1), allLabel: z.string().min(1), allValue: z.string().min(1) }), platform: z.object({ control: z.string().min(1), id: z.string().min(1), label: z.string().min(1), value: z.string().min(1), allLabel: z.string().min(1), allValue: z.string().min(1), options: z.array(optionSchema).min(1) }), sort: z.object({ label: z.string().min(1), value: z.string().min(1), options: z.array(optionSchema).min(1) }), view: viewControlSchema }), sidebar: z.object({ label: z.string().min(1), filterLabel: z.string().min(1), category: filterGroupSchema, platform: filterGroupSchema, price: z.record(z.string(), z.unknown()).optional(), license: z.record(z.string(), z.unknown()).optional(), ratings: z.record(z.string(), z.unknown()).optional(), advertisement: z.object({ title: z.string().min(1), description: z.string().min(1), image: imageSchema, action: pageActionSchema }) }), itemPresentation: productCardPresentationSchema, result: z.object({ label: z.string().min(1) }), cards: pageCardConfigSchema, emptyLabel: z.string().min(1), pagination: paginationSchema }) });
const blogArchiveSectionSchema = z.object({ id: z.string().min(1), type: z.literal("archive"), template: z.literal("faceted"), settings: pageSectionSettingsSchema, content: z.object({ source: z.object({ collection: z.literal("blog") }), toolbar: z.object({ search: searchControlSchema, category: z.object({ control: z.string().min(1), id: z.string().min(1), label: z.string().min(1), allLabel: z.string().min(1), allValue: z.string().min(1) }), sort: z.object({ label: z.string().min(1), value: z.string().min(1), options: z.array(optionSchema).min(1) }), view: viewControlSchema }), sidebar: z.object({ label: z.string().min(1), filter: z.object({ legend: z.string().min(1), allLabel: z.string().min(1) }), featured: z.object({ title: z.string().min(1), limit: z.number().int().positive(), cards: pageCardConfigSchema }), newsletter: z.object({ template: z.enum(["form-first", "media-first"]), title: z.string().min(1), description: z.string().min(1), image: imageSchema, action: pageActionSchema, form: z.object({ formName: z.string().min(1), inputId: z.string().min(1), inputLabel: z.string().min(1), placeholder: z.string().min(1), submitLabel: z.string().min(1), tone: z.enum(["dark", "light"]).optional() }) }) }), itemPresentation: insightCardPresentationSchema, result: z.object({ title: z.string().min(1) }), cards: pageCardConfigSchema, emptyLabel: z.string().min(1), pagination: paginationSchema }) });

const heroSectionSchema = z.object({ id: z.string().min(1), type: z.literal("hero"), template: z.literal("split-media"), settings: pageSectionSettingsSchema, content: z.object({ id: z.string().optional(), eyebrow: z.string().optional(), title: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]), accent: z.string().optional(), description: z.string().optional(), image: imageSchema.optional(), actions: z.array(pageActionSchema).optional(), actionsLabel: z.string().optional(), socialLinks: z.array(socialLinkSchema).optional(), scrollLabel: z.string().optional() }) });
const pageHeaderSectionSchema = z.object({ id: z.string().min(1), type: z.literal("page-header"), template: z.enum(["split-media", "split-benefits", "immersive"]), settings: pageSectionSettingsSchema, content: z.object({ id: z.string().optional(), title: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]).optional(), description: z.string().optional(), eyebrow: z.string().optional(), accent: z.string().optional(), image: imageSchema.optional(), source: z.object({ collection: z.literal("blog") }).optional(), breadcrumb: z.object({ label: z.string().min(1), items: z.array(navigationItemSchema), current: z.string().min(1) }).optional(), benefits: z.union([z.object({ items: z.array(z.object({ label: z.string().min(1), icon: z.string().min(1) })).min(1) }), z.object({ articleLabel: z.string().min(1), topicLabel: z.string().min(1), minuteLabel: z.string().min(1) })]).optional(), actionsLabel: z.string().optional(), actions: z.array(pageActionSchema).optional(), quote: z.string().optional(), quoteCredit: z.string().optional(), metrics: z.array(z.object({ label: z.string().min(1), value: z.string().min(1), icon: z.string().min(1) })).optional() }) });
const articleSectionSchema = z.object({ id: z.string().min(1), type: z.literal("article"), template: z.string().optional(), settings: pageSectionSettingsSchema, content: z.object({ blocks: z.array(z.object({ id: z.string().min(1), title: z.string().min(1), paragraphs: z.array(z.string().min(1)).min(1) })).min(1) }) });
const ctaSectionSchema = z.object({ id: z.string().min(1), type: z.literal("cta"), template: z.enum(["callout", "default", "media-pricing", "subscription"]), settings: pageSectionSettingsSchema, content: z.object({ id: z.string().optional(), title: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]), description: z.string().optional(), action: pageActionSchema.optional(), image: imageSchema.optional(), features: z.object({ items: z.array(z.object({ label: z.string().min(1), icon: z.string().min(1) })).min(1) }).optional(), price: z.object({ current: z.string().min(1), period: z.string().optional(), previous: z.string().optional() }).optional(), form: z.object({ formName: z.string().min(1), inputId: z.string().min(1), inputLabel: z.string().min(1), placeholder: z.string().min(1), submitLabel: z.string().min(1), tone: z.enum(["dark", "light"]).optional() }).optional() }) });

export const pageSectionSchema = z.union([staticCollectionSectionSchema, productsCollectionSectionSchema, projectsCollectionSectionSchema, labsCollectionSectionSchema, blogCollectionSectionSchema, comicsCollectionSectionSchema, novelsCollectionSectionSchema, publicationsCollectionSectionSchema, projectsArchiveSectionSchema, labsArchiveSectionSchema, productsArchiveSectionSchema, blogArchiveSectionSchema, heroSectionSchema, pageHeaderSectionSchema, articleSectionSchema, ctaSectionSchema]);

const pageLayoutSchema = z.object({ template: z.enum(["fluid", "contained", "boxed", "sidebar", "centered"]), containerSize: z.enum(["site", "content"]).optional(), asideLabel: z.string().min(1).optional(), asidePosition: z.enum(["start", "end"]).optional() });
const detailSectionSettingsSchema = z.object({ theme: z.enum(["dark", "light", "canvas", "accent", "none"]), spacing: z.enum(["compact", "default", "none", "lead", "body", "closing"]), container: z.enum(["site", "content", "none"]) });
const productActionSchema = z.object({ label: z.string().min(1), href: z.string().min(1), icon: z.string().optional(), variant: z.string().optional() });
const productDetailPageSchema = z.object({ template: z.enum(["fluid", "contained", "boxed", "sidebar", "centered"]), sections: z.array(z.discriminatedUnion("type", [
  z.object({ id: z.string().min(1), type: z.literal("page-header"), template: z.literal("gallery-summary"), settings: detailSectionSettingsSchema, content: z.object({ breadcrumbLabel: z.string().min(1), productsLabel: z.string().min(1), galleryLabel: z.string().min(1), thumbnailLabel: z.string().min(1), salesLabel: z.string().min(1), features: z.array(z.record(z.string(), z.unknown())), facts: z.array(z.object({ label: z.string().min(1), value: z.string().min(1) })), actionsLabel: z.string().min(1), actions: z.array(productActionSchema), paymentLabel: z.string().min(1), paymentMethods: z.array(z.unknown()) }) }),
  z.object({ id: z.string().min(1), type: z.literal("article"), template: z.string().optional(), settings: detailSectionSettingsSchema, content: z.object({ blocks: z.array(z.object({ id: z.string().min(1), title: z.string().min(1), paragraphs: z.array(z.string().min(1)).min(1) })).min(1) }) }),
])) });

export const pageSchema = z.object({ slug: z.string(), meta: z.object({ title: z.string(), description: z.string().optional(), author: z.string().optional(), publishedAt: z.string().optional(), updatedAt: z.string().optional() }), seo: z.record(z.string(), z.unknown()).nullable().optional(), content: z.object({ layout: pageLayoutSchema, sections: z.array(pageSectionSchema) }) });
export const closingProfileSettingsSchema = z.object({ id: z.string().min(1), eyebrow: z.string().min(1), nameLines: z.array(z.string().min(1)).min(1), roleLabel: z.string().min(1), followAction: z.object({ label: z.string().min(1), href: z.string().min(1) }), emailActionLabel: z.string().min(1), locationLabel: z.string().min(1), portraits: z.object({ collapsed: imageSchema, expanded: imageSchema }).optional() });
export const interfaceSettingsSchema = z.object({ skipToContent: z.string().min(1), backToTop: z.string().min(1), openMenu: z.string().min(1), closeMenu: z.string().min(1), loadingScreen: z.object({ label: z.string().min(1), status: z.string().min(1), tips: z.array(z.string().min(1)).min(1), holdOpen: z.boolean(), progressLabel: z.string().min(1), image: imageSchema }), navigation: z.object({ primaryLabel: z.string().min(1), mobileLabel: z.string().min(1), socialLabel: z.string().min(1), footerSocialLabel: z.string().min(1), railSocialDisplay: z.enum(["label", "shortLabel", "icon"]) }), progress: z.object({ railLabel: z.string().min(1), readingLabel: z.string().min(1), initialSection: z.string().min(1), initialValue: z.string().min(1) }), separators: z.object({ slash: z.string(), dot: z.string() }), contentFormatting: z.object({ readingTimeTemplate: z.string().includes("{minutes}"), dateLocale: z.string().min(2) }) });

export const productEntrySchema = z.object({ id: z.number().int().positive(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().min(1), category: z.string().min(1), categorySlug: z.string().min(1), platform: z.string().min(1), description: z.string().min(1), price: z.number().nonnegative(), oldPrice: z.number().nonnegative().optional(), rating: z.number().min(0).max(5), reviews: z.number().int().nonnegative(), badge: z.string().optional(), image: z.string().min(1), detail: z.object({ page: productDetailPageSchema }) });
export const footerSettingsSchema = z.object({ brandDescription: z.string().min(1), socialDisplay: z.enum(["label", "shortLabel", "icon"]), menuLabel: z.string().min(1), resourcesLabel: z.string().min(1), legalLabel: z.string().min(1), locationLabel: z.string().min(1), copyrightSymbol: z.string().min(1), buildLabel: z.string().min(1), newsletter: z.object({ label: z.string().min(1), description: z.string().min(1), inputLabel: z.string().min(1), placeholder: z.string().min(1), submitLabel: z.string().min(1) }) });
export const systemStatesSettingsSchema = z.object({ notFound: systemStateSchema, empty: systemStateSchema });
